[package]
name = "day07"
authors.workspace = true
description.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
once_cell.workspace = true
regex.workspace = true
thiserror.workspace = true
